#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mypy_extensions
Version  : 0.4.2
Release  : 5
URL      : https://files.pythonhosted.org/packages/1e/2f/7bba47eb58f62a473387cd7658dedd0bedb4b0fa9d530bbbfa0a6d23034a/mypy_extensions-0.4.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/1e/2f/7bba47eb58f62a473387cd7658dedd0bedb4b0fa9d530bbbfa0a6d23034a/mypy_extensions-0.4.2.tar.gz
Summary  : Experimental type system extensions for programs checked with the mypy typechecker.
Group    : Development/Tools
License  : MIT
Requires: mypy_extensions-license = %{version}-%{release}
Requires: mypy_extensions-python = %{version}-%{release}
Requires: mypy_extensions-python3 = %{version}-%{release}
Requires: typing
BuildRequires : buildreq-distutils3
BuildRequires : typing

%description
Mypy Extensions
===============
The "mypy_extensions" module defines experimental extensions to the
standard "typing" module that are supported by the mypy typechecker.

%package license
Summary: license components for the mypy_extensions package.
Group: Default

%description license
license components for the mypy_extensions package.


%package python
Summary: python components for the mypy_extensions package.
Group: Default
Requires: mypy_extensions-python3 = %{version}-%{release}

%description python
python components for the mypy_extensions package.


%package python3
Summary: python3 components for the mypy_extensions package.
Group: Default
Requires: python3-core

%description python3
python3 components for the mypy_extensions package.


%prep
%setup -q -n mypy_extensions-0.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570194699
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mypy_extensions
cp LICENSE %{buildroot}/usr/share/package-licenses/mypy_extensions/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mypy_extensions/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
