#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mypy_extensions
Version  : 0.4.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/c2/92/3cc05d1206237d54db7b2565a58080a909445330b4f90a6436302a49f0f8/mypy_extensions-0.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/c2/92/3cc05d1206237d54db7b2565a58080a909445330b4f90a6436302a49f0f8/mypy_extensions-0.4.1.tar.gz
Summary  : Experimental type system extensions for programs checked with the mypy typechecker.
Group    : Development/Tools
License  : MIT
Requires: mypy_extensions-python3
Requires: mypy_extensions-license
Requires: mypy_extensions-python
Requires: typing
BuildRequires : buildreq-distutils3
BuildRequires : typing

%description
===============
        
        The "mypy_extensions" module defines experimental extensions to the
        standard "typing" module that are supported by the mypy typechecker.

%package license
Summary: license components for the mypy_extensions package.
Group: Default

%description license
license components for the mypy_extensions package.


%package python
Summary: python components for the mypy_extensions package.
Group: Default
Requires: mypy_extensions-python3

%description python
python components for the mypy_extensions package.


%package python3
Summary: python3 components for the mypy_extensions package.
Group: Default
Requires: python3-core

%description python3
python3 components for the mypy_extensions package.


%prep
%setup -q -n mypy_extensions-0.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537259856
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/mypy_extensions
cp LICENSE %{buildroot}/usr/share/doc/mypy_extensions/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/mypy_extensions/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
